import type { Clinic } from '../types/clinic';

export const MAX_BACKGROUND_GEOFENCE_REGIONS = 20;

export const CLINIC_DIRECTORY: Clinic[] = [
  {
    id: 'clinic-01',
    code: 'LGM-001',
    name: 'Yaba Central Clinic',
    region: 'Lagos Mainland',
    city: 'Lagos',
    address: '12 Herbert Macaulay Way, Yaba',
    managerName: 'Dr. Simisola Adeniran',
    staffCount: 28,
    isActive: true,
    geofence: { latitude: 6.5095, longitude: 3.3713, radiusMeters: 120, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-02',
    code: 'LGM-002',
    name: 'Surulere Family Clinic',
    region: 'Lagos Mainland',
    city: 'Lagos',
    address: '48 Bode Thomas Street, Surulere',
    managerName: 'Dr. Nkiruka Balogun',
    staffCount: 24,
    isActive: true,
    geofence: { latitude: 6.5001, longitude: 3.3439, radiusMeters: 130, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-03',
    code: 'LGM-003',
    name: 'Maryland Primary Care',
    region: 'Lagos Mainland',
    city: 'Lagos',
    address: '21 Ikorodu Road, Maryland',
    managerName: 'Dr. Chinenye Obi',
    staffCount: 31,
    isActive: true,
    geofence: { latitude: 6.5702, longitude: 3.3759, radiusMeters: 125, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-04',
    code: 'LGM-004',
    name: 'Gbagada Junction Clinic',
    region: 'Lagos Mainland',
    city: 'Lagos',
    address: '5 Diya Street, Gbagada',
    managerName: 'Dr. Kemi Olatunji',
    staffCount: 22,
    isActive: true,
    geofence: { latitude: 6.5532, longitude: 3.3853, radiusMeters: 120, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-05',
    code: 'LGM-005',
    name: 'Festac Community Clinic',
    region: 'Lagos Mainland',
    city: 'Lagos',
    address: '7th Avenue, Festac Town',
    managerName: 'Dr. Ugochi Iweala',
    staffCount: 20,
    isActive: true,
    geofence: { latitude: 6.4697, longitude: 3.2825, radiusMeters: 140, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-06',
    code: 'LGM-006',
    name: 'Apapa Port Clinic',
    region: 'Lagos Mainland',
    city: 'Lagos',
    address: '23 Wharf Road, Apapa',
    managerName: 'Dr. Tunde Shittu',
    staffCount: 18,
    isActive: true,
    geofence: { latitude: 6.4484, longitude: 3.3651, radiusMeters: 115, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-07',
    code: 'LGI-001',
    name: 'Victoria Island Executive Clinic',
    region: 'Lagos Island',
    city: 'Lagos',
    address: '17 Ahmadu Bello Way, Victoria Island',
    managerName: 'Dr. Amina Idris',
    staffCount: 26,
    isActive: true,
    geofence: { latitude: 6.4281, longitude: 3.4219, radiusMeters: 110, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-08',
    code: 'LGI-002',
    name: 'Ikoyi Harbour Clinic',
    region: 'Lagos Island',
    city: 'Lagos',
    address: '9 Bourdillon Road, Ikoyi',
    managerName: 'Dr. Moyin Adebayo',
    staffCount: 21,
    isActive: true,
    geofence: { latitude: 6.4473, longitude: 3.4371, radiusMeters: 115, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-09',
    code: 'LGI-003',
    name: 'Marina Civic Clinic',
    region: 'Lagos Island',
    city: 'Lagos',
    address: '2 Broad Street, Marina',
    managerName: 'Dr. Kehinde Bello',
    staffCount: 19,
    isActive: true,
    geofence: { latitude: 6.4518, longitude: 3.3952, radiusMeters: 118, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-10',
    code: 'LGI-004',
    name: 'Lekki Phase One Clinic',
    region: 'Lagos Island',
    city: 'Lagos',
    address: '14 Admiralty Way, Lekki Phase 1',
    managerName: 'Dr. Ifeoma Eze',
    staffCount: 27,
    isActive: true,
    geofence: { latitude: 6.4422, longitude: 3.4728, radiusMeters: 125, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-11',
    code: 'LGI-005',
    name: 'Oniru Waterfront Clinic',
    region: 'Lagos Island',
    city: 'Lagos',
    address: '8 Oniru Market Road, Oniru',
    managerName: 'Dr. Gbenga Afolayan',
    staffCount: 17,
    isActive: true,
    geofence: { latitude: 6.4351, longitude: 3.4515, radiusMeters: 112, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-12',
    code: 'LGI-006',
    name: 'Ajah Gateway Clinic',
    region: 'Lagos Island',
    city: 'Lagos',
    address: '45 Lekki-Epe Expressway, Ajah',
    managerName: 'Dr. Temitope Asika',
    staffCount: 23,
    isActive: true,
    geofence: { latitude: 6.4699, longitude: 3.5852, radiusMeters: 140, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-13',
    code: 'IKJ-001',
    name: 'Ikeja GRA Clinic',
    region: 'Ikeja Corridor',
    city: 'Lagos',
    address: '3 Isaac John Street, GRA Ikeja',
    managerName: 'Dr. Olabisi Adedeji',
    staffCount: 29,
    isActive: true,
    geofence: { latitude: 6.5862, longitude: 3.3578, radiusMeters: 120, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-14',
    code: 'IKJ-002',
    name: 'Alausa Secretariat Clinic',
    region: 'Ikeja Corridor',
    city: 'Lagos',
    address: 'Governor Road, Alausa',
    managerName: 'Dr. Dayo Akinola',
    staffCount: 18,
    isActive: true,
    geofence: { latitude: 6.6175, longitude: 3.349, radiusMeters: 118, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-15',
    code: 'IKJ-003',
    name: 'Ogba Junction Clinic',
    region: 'Ikeja Corridor',
    city: 'Lagos',
    address: '16 Obawole Road, Ogba',
    managerName: 'Dr. Rukayat Bello',
    staffCount: 16,
    isActive: true,
    geofence: { latitude: 6.6421, longitude: 3.3426, radiusMeters: 122, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-16',
    code: 'IKJ-004',
    name: 'Ojodu Primary Clinic',
    region: 'Ikeja Corridor',
    city: 'Lagos',
    address: '22 Berger Bus Stop, Ojodu',
    managerName: 'Dr. Olamide Fashola',
    staffCount: 20,
    isActive: true,
    geofence: { latitude: 6.6493, longitude: 3.3601, radiusMeters: 125, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-17',
    code: 'IKJ-005',
    name: 'Anthony Medical Hub',
    region: 'Ikeja Corridor',
    city: 'Lagos',
    address: '30 Mobolaji Bank Anthony Way',
    managerName: 'Dr. Halima Yusuf',
    staffCount: 25,
    isActive: true,
    geofence: { latitude: 6.5713, longitude: 3.3542, radiusMeters: 120, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-18',
    code: 'IKJ-006',
    name: 'Mile 12 Transit Clinic',
    region: 'Ikeja Corridor',
    city: 'Lagos',
    address: '1 Ikorodu Motor Road, Ketu',
    managerName: 'Dr. Funke Adisa',
    staffCount: 18,
    isActive: true,
    geofence: { latitude: 6.5989, longitude: 3.3866, radiusMeters: 130, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-19',
    code: 'LEK-001',
    name: 'Chevron Axis Clinic',
    region: 'Lekki Axis',
    city: 'Lagos',
    address: '18 Chevron Drive, Lekki',
    managerName: 'Dr. Sonia Adekoya',
    staffCount: 22,
    isActive: true,
    geofence: { latitude: 6.4412, longitude: 3.5348, radiusMeters: 140, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-20',
    code: 'LEK-002',
    name: 'Ikota Community Clinic',
    region: 'Lekki Axis',
    city: 'Lagos',
    address: '12 Ikota Shopping Complex',
    managerName: 'Dr. Rita Ekwueme',
    staffCount: 19,
    isActive: true,
    geofence: { latitude: 6.4658, longitude: 3.5584, radiusMeters: 145, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-21',
    code: 'LEK-003',
    name: 'Sangotedo Care Centre',
    region: 'Lekki Axis',
    city: 'Lagos',
    address: '28 Monastery Road, Sangotedo',
    managerName: 'Dr. Daniel Nnaji',
    staffCount: 15,
    isActive: true,
    geofence: { latitude: 6.4722, longitude: 3.6152, radiusMeters: 150, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-22',
    code: 'LEK-004',
    name: 'Abijo Coast Clinic',
    region: 'Lekki Axis',
    city: 'Lagos',
    address: '6 Coastal Road, Abijo',
    managerName: 'Dr. Promise Ekanem',
    staffCount: 14,
    isActive: true,
    geofence: { latitude: 6.4894, longitude: 3.6636, radiusMeters: 155, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-23',
    code: 'LEK-005',
    name: 'Epe Growth Clinic',
    region: 'Lekki Axis',
    city: 'Lagos',
    address: '41 Lagos Road, Epe',
    managerName: 'Dr. Mariam Adeyemi',
    staffCount: 12,
    isActive: true,
    geofence: { latitude: 6.5841, longitude: 3.9839, radiusMeters: 170, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-24',
    code: 'ABJ-001',
    name: 'Wuse District Clinic',
    region: 'Abuja',
    city: 'Abuja',
    address: '14 Adetokunbo Ademola Crescent, Wuse II',
    managerName: 'Dr. Salman Garba',
    staffCount: 30,
    isActive: true,
    geofence: { latitude: 9.0782, longitude: 7.4811, radiusMeters: 125, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-25',
    code: 'ABJ-002',
    name: 'Garki One Clinic',
    region: 'Abuja',
    city: 'Abuja',
    address: '8 Tafawa Balewa Way, Garki',
    managerName: 'Dr. Hauwa Suleiman',
    staffCount: 27,
    isActive: true,
    geofence: { latitude: 9.0355, longitude: 7.4893, radiusMeters: 120, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-26',
    code: 'ABJ-003',
    name: 'Maitama Executive Clinic',
    region: 'Abuja',
    city: 'Abuja',
    address: '2 Limpopo Street, Maitama',
    managerName: 'Dr. Kelechi Okonkwo',
    staffCount: 18,
    isActive: true,
    geofence: { latitude: 9.0894, longitude: 7.5031, radiusMeters: 118, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-27',
    code: 'ABJ-004',
    name: 'Lugbe Family Clinic',
    region: 'Abuja',
    city: 'Abuja',
    address: 'Airport Road, Lugbe',
    managerName: 'Dr. Fatima Goni',
    staffCount: 16,
    isActive: true,
    geofence: { latitude: 8.9926, longitude: 7.3566, radiusMeters: 145, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-28',
    code: 'ABJ-005',
    name: 'Kubwa Civic Clinic',
    region: 'Abuja',
    city: 'Abuja',
    address: '18 Arab Road, Kubwa',
    managerName: 'Dr. Sunday Ezeh',
    staffCount: 15,
    isActive: true,
    geofence: { latitude: 9.1518, longitude: 7.3238, radiusMeters: 150, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-29',
    code: 'ABJ-006',
    name: 'Jabi Lake Clinic',
    region: 'Abuja',
    city: 'Abuja',
    address: '26 Bala Sokoto Way, Jabi',
    managerName: 'Dr. Deborah Mbanefo',
    staffCount: 17,
    isActive: true,
    geofence: { latitude: 9.0768, longitude: 7.4191, radiusMeters: 124, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-30',
    code: 'PHC-001',
    name: 'GRA Port Harcourt Clinic',
    region: 'Port Harcourt',
    city: 'Port Harcourt',
    address: '11 Aba Road, GRA Phase 2',
    managerName: 'Dr. Blessing Jaja',
    staffCount: 23,
    isActive: true,
    geofence: { latitude: 4.8156, longitude: 7.0243, radiusMeters: 120, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-31',
    code: 'PHC-002',
    name: 'Rumuola Community Clinic',
    region: 'Port Harcourt',
    city: 'Port Harcourt',
    address: '20 Rumuola Link Road',
    managerName: 'Dr. Iyke Dike',
    staffCount: 19,
    isActive: true,
    geofence: { latitude: 4.8464, longitude: 7.0124, radiusMeters: 126, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-32',
    code: 'PHC-003',
    name: 'Trans Amadi Industrial Clinic',
    region: 'Port Harcourt',
    city: 'Port Harcourt',
    address: '9 Eastern Bypass, Trans Amadi',
    managerName: 'Dr. Angela Cookey',
    staffCount: 21,
    isActive: true,
    geofence: { latitude: 4.8035, longitude: 7.0502, radiusMeters: 118, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-33',
    code: 'PHC-004',
    name: 'Woji Waterfront Clinic',
    region: 'Port Harcourt',
    city: 'Port Harcourt',
    address: '15 Woji Road, Woji',
    managerName: 'Dr. Tamarapreye Briggs',
    staffCount: 14,
    isActive: true,
    geofence: { latitude: 4.8585, longitude: 7.0828, radiusMeters: 132, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-34',
    code: 'ZMT-G',
    name: 'ZMT Gulshan',
    region: 'Karachi',
    city: 'Karachi',
    address: 'FL-6, 6, Block 4 Block 04 Gulshan-e-Iqbal, Karachi, 75300, Pakistan',
    managerName: 'Dr. Hina Qureshi',
    staffCount: 16,
    isActive: true,
    geofence: { latitude: 24.9004884, longitude: 67.0824283, radiusMeters: 120, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-35',
    code: 'ZMT-B',
    name: 'ZMT Bahadurabad',
    region: 'Karachi',
    city: 'Karachi',
    address: '25 Bahadur Shah Zafar Road, Bahadurabad, Karachi, Pakistan',
    managerName: 'Dr. Sana Farooq',
    staffCount: 18,
    isActive: true,
    geofence: { latitude: 24.8829, longitude: 67.0688, radiusMeters: 120, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-36',
    code: 'ZMT-C',
    name: 'ZMT Clifton',
    region: 'Karachi',
    city: 'Karachi',
    address: 'Block 5 Clifton, Karachi, Pakistan',
    managerName: 'Dr. Areeba Malik',
    staffCount: 21,
    isActive: true,
    geofence: { latitude: 24.8137, longitude: 67.0305, radiusMeters: 125, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-37',
    code: 'ZMT-D',
    name: 'ZMT DHA',
    region: 'Karachi',
    city: 'Karachi',
    address: 'Khayaban-e-Shahbaz, DHA Phase 6, Karachi, Pakistan',
    managerName: 'Dr. Aliya Siddiqui',
    staffCount: 19,
    isActive: true,
    geofence: { latitude: 24.8004, longitude: 67.0657, radiusMeters: 130, notifyOnEnter: true, notifyOnExit: true },
  },
  {
    id: 'clinic-38',
    code: 'ZMT-N',
    name: 'ZMT North Nazimabad',
    region: 'Karachi',
    city: 'Karachi',
    address: 'Block H North Nazimabad, Karachi, Pakistan',
    managerName: 'Dr. Usman Hafeez',
    staffCount: 17,
    isActive: true,
    geofence: { latitude: 24.9387, longitude: 67.0436, radiusMeters: 128, notifyOnEnter: true, notifyOnExit: true },
  },
];

export const CLINIC_LOOKUP = Object.fromEntries(CLINIC_DIRECTORY.map((clinic) => [clinic.id, clinic])) as Record<string, Clinic>;

export const getClinicById = (clinicId?: string) => (clinicId ? CLINIC_LOOKUP[clinicId] : undefined);

export const getClinicNameById = (clinicId?: string) => getClinicById(clinicId)?.name ?? 'Unassigned clinic';